version: '3'
services:
  eosf:
    build: .
    image: sebastianmontero/eosf
    container_name: eosf
    ports:
     - "127.0.0.1:8888:8888"
    volumes:
     - ~/eos-workspace:/workspace
     - eos-contracts:/eos/contracts
     - eos-externals:/eos/externals
     - usr-include:/usr/local/include
     - boost:/root/opt/boost/include
     - eosfactory:/eosfactory
    env_file: eosf.env
    stdin_open: true


volumes:
  eos-contracts:
  eos-externals:
  usr-include:
  boost:
  eosfactory:
